name: Push Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run setup script
        run: ./setup.sh

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Determine ORFS tag
        id: get_tag
        run: |
          cd OpenROAD-flow-scripts
          tag=$(git describe --tags --abbrev=8 2>/dev/null || echo "latest")
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Find and list all designs
        run: |
          echo "Finding all design configurations..."
          configs=$(find designs/nangate45 designs/asap7 designs/sky130hd -name config.mk | sort)
          
          echo ""
          echo "===================="
          echo "DESIGNS TO BE RUN:"
          echo "===================="
          
          count=0
          for config in $configs; do
            ((count++))
            echo "$count. $config"
          done
          
          echo ""
          echo "Total designs found: $count"
          echo "===================="

      - name: Run ORFS for all designs
        run: |
            tag="${{ steps.get_tag.outputs.tag }}"
            docker run --rm \
            -v ${{ github.workspace }}/OpenROAD-flow-scripts/flow:/OpenROAD-flow-scripts/flow \
            -v ${{ github.workspace }}:/OpenROAD-flow-scripts/UCSC_ML_suite \
            -w /OpenROAD-flow-scripts \
            openroad/orfs:$tag \
            bash -c '
                set +e
                git config --global --add safe.directory "*"
                cd UCSC_ML_suite

                # Initialize counters
                success_count=0
                failure_count=0
                total_count=0

                configs=$(find designs/nangate45 designs/asap7 designs/sky130hd -name config.mk | sort)

                for config in $configs; do
                    echo ""
                    echo "===================="
                    echo "Running design: $config"
                    echo "===================="
                    
                    ((total_count++))
                    
                    if make DESIGN_CONFIG="$config"; then
                        echo "Design $config completed successfully"
                        ((success_count++))
                    else
                        exit_code=$?
                        echo "Design $config failed (exit code: $exit_code)"
                        ((failure_count++))
                        echo "Continuing with remaining designs..."
                    fi
                done

                echo ""
                echo "===================="
                echo "SUMMARY:"
                echo "Total designs: $total_count"
                echo "Successful: $success_count"
                echo "Failed: $failure_count"
                echo "===================="
                
                exit 0
            '

      - name: Extract and update results
        run: |
            echo "Extracting results from OpenROAD runs..."
            
            # Check if the script exists
            if [ ! -f "extract_results.py" ]; then
                echo "Error: extract_results.py not found"
                exit 1
            fi
            
            # Run the extraction script
            if python3 extract_results.py --base-dir . --output QOR.md; then
                echo "Results extraction completed successfully"
            else
                echo "Results extraction failed, but continuing with workflow"
                echo "This may happen if no designs completed or there were format issues"
            fi
            
            # Show a preview of the results
            echo "Generated results table preview:"
            if grep -A 10 "OpenROAD Flow Results" QOR.md; then
                echo "Results table successfully updated"
            else
                echo "No results table found in QOR.md"
            fi
            
            # Show summary statistics
            if [ -d "logs" ]; then
                total_reports=$(find logs -name "6_report.json" | wc -l)
                echo "Found $total_reports completed design runs"
            fi

      - name: Commit and push results
        run: |
            echo "Current ref: ${{ github.ref }}"
            echo "Branch: ${{ github.ref_name }}"
            
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                echo "Running on main branch - will commit results"
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                
                # Check if there are any changes to commit
                if git diff --quiet; then
                    echo "No changes to commit"
                else
                    git add QOR.md
                    git commit -m "Update OpenROAD flow results [skip ci]" || echo "No changes to commit"
                    git push
                fi
            else
                echo "Skipping commit - not on main branch (current: ${{ github.ref }})"
            fi
